---
title: Expressions
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
headline: 'User Experience Design Studio

'
description: Expressions is a user experience agency that helps lifestyle inspired
  companies engage consumers and communicate with users with best practice.
logo: "/images/expressions_logo.png"
owner: Information Business
first_published: 2016
email: ipay@ib.sa
baseurl: 
url: http://expressions.io
project-url: http://ib.sa/projects/expressions
contact-url: http://ib.sa/#contact
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
markdown: kramdown
