# Welcome to Jekyll!
#

# Site settings
title: Expressions
headline: |
  User Experience Design Studio
description: Expressions is a user experience agency that helps lifestyle inspired companies engage consumers and communicate with users with best practice.
logo: /images/expressions_logo_white.png
owner: Information Business # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: ipay@ib.sa
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://expressions.io" # the base hostname & protocol for your site
project-url: http://ib.sa/projects/expressions
contact-url: http://ib.sa/#contact
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
